### ISSUE TITLE
ifrextract hangs up and ends up creating an unending txt file

### ISSUE THREAD

**Issue by the-braveknight** [LongSoft/Universal-IFR-Extractor#10]
Here's my ROM image
[IFR.rom.zip](https://github.com/LongSoft/Universal-IFR-Extractor/files/2342545/IFR.rom.zip)

Here's what the resulting txt file looks like:
![screen shot 2018-09-01 at 5 39 57 pm](https://user-images.githubusercontent.com/14353085/44948272-68caa700-ae23-11e8-917b-53ffb232797f.png)

**Comment by vit9696** [comment]
Added a hack to avoid the hang.

**Comment by dsanke** [comment]
[Lenovo_M700_Setup.zip](https://github.com/LongSoft/Universal-IFR-Extractor/files/9542569/Lenovo_M700_Setup.zip)
Found the same problem.

0x22974		Setup (0x7 from string package 0x0)
0x332E4		0 (0x100 from string package 0x0)

Fount it caused by a wrong from set detected. It detected form set during other form set.
Fixed by this:
in UEFI.cpp getUEFIFormSets function:
add "i += tempFormSet.header.length;" before loop end.
