### ISSUE TITLE
Variables view

### ISSUE THREAD

**Issue by mirh** [LongSoft/Universal-IFR-Extractor#23]
I don't think it's a secret what most users are using this program for. 
It would be nice if instead of the "proper" decoding with all the pseudo-code and structures, there was also something idiot-proof like [this](https://github.com/BoringBoredom/IFR-Formatter), where variables are the "root" of the tree list rather than the last branch.

**Comment by Falcosc** [comment]
I took me a while to discover this capability. In the past, the only solution was to do a sketchy BIOS unlock. I tried to spread the existence of this tool a bit more in spaces of BIOS unlocking request since it was difficult to find it.

For me, it is good enough to have any solution. So it's ok to use this code https://github.com/BoringBoredom/UEFI-Editor/blob/master/assets/js/main.js

But because this is dependent on the output from @vit9696 I would appreciate if you could ping @BoringBoredom if there are changes in the text output to give him more time to react.

**Comment by NikolajSchlej** [comment]
@mirh, you can create an issue in IFRExtractor-RS repo on creating a prettier output format, but it looks like 3rd-party tools already cover that well enough.
