### ISSUE TITLE
ifrextract shows UNKNOWN Protocol on HUANANZHI-X99-F8

### ISSUE THREAD

**Issue by shiecldk** [LongSoft/Universal-IFR-Extractor#24]
Environment: MacBook Air M1, Apple Siliicon, ifrextract version 0.3.7

When extracting the stock HUANANZHI-X99-F8 UEFI BIOS (read from CH341A) with 
`./ifrextract ./X99F8_Backup.bin ./X99F8_Backup.txt`,
it reports:
`Input: ./X99F8_Backup.bin`
`Output: ./X99F8_Backup.txt`
`Protocol: UNKNOWN`
`error: Unknown protocol`
and no file is output.

With the modified UEFI BIOS, CX99DE29.BIN, from https://github.com/BIOS-iEngineer/HUANANZHI-X99-F8-2021,
`./ifrextract ./CX99DE29.bin ./CX99DE29.txt`,
it shows:
`Input: ./CX99DE29.BIN`
`Output: ./CX99DE29.txt`
`Protocol: UEFI`;
however, ifrextract only putouts the Realtek Ethernet Controller report (see the attached file).

The files are attached here:
[HUANANZHI-X99-F8.zip](https://github.com/LongSoft/Universal-IFR-Extractor/files/7834176/HUANANZHI-X99-F8.zip)

**Comment by Jero-CJQ** [comment]
I have a same difficulty

**Comment by mirh** [comment]
That's.. normal I think?

Due to some happenstance, parsing the second image somehow can read directly 2851E234-20FD-4D1E-9041-DCB8F3025CAE (which is the realtek driver.. the first one has the same content inside 8D59EBC8-B85E-400E-970A-1F995D1DB587). 
But you should feed the program with individual dxes, not the whole ass bios blob.

**Comment by NikolajSchlej** [comment]
Yep, the tool is supposed to consume an individual binary file, not the whole BIOS image.
