### ISSUE TITLE
Migrate to IFRExtractor-RS

### ISSUE THREAD

**Issue by vit9696** [LongSoft/Universal-IFR-Extractor#28]
Should happen once feature parity is reached: https://github.com/LongSoft/IFRExtractor-RS/issues/6. Please file issues in https://github.com/LongSoft/IFRExtractor-RS, where applicable.

**Comment by Falcosc** [comment]
Why did you divide these 2 tools? I mean, why is migrating to IFRExtractor-RS a goal, in the end all started with donovan6000 contribution.

Great work, we appreciate the work of all people who got involved in the tools.

**Comment by NikolajSchlej** [comment]
We all appreciate D6K being the pioneer here, but the original code is approaching unmaintainable state for us. 

There are a bunch of bugs that are impossible to fix without a complete rewrite, and IFRExtractor-RS is that rewrite already, so once feature-parity is reached, we will stop supporting this for and archive this repo.

To be honest, I've already did this once, but @vit9696 reminded me of some fairly recent UEFI implementation that still use Framework-compatible HII definitions from 2007, so I reverted the archiving. However, I will not be supporting this repo anymore or react on bugs reported for it, and it's up for @vit9696 to do it, if he wishes.

It is not about dunking on D6K's legacy or trying to monopolise IFR-to-text area, just about us being busy with day jobs and real life, and limiting the amount of things we need to spend time and effort on.

**Comment by Falcosc** [comment]
That could be an issue since Universal-IFR-Extractor is part of documentations like that:
https://github.com/BoringBoredom/UEFI-Editor#readme

Which product generations are not supported by IFRExtractor-RS?
If IFRExtractor-RS is mainline, I would consider using IFRExtractor-RS in my documentations, since I shared your great tools a bit more because I really had trouble to find them. But I need to know which features are missing in the RS one. Do the missing features affect the capability to find out which mainboard have bifurcation settings?

**Comment by NikolajSchlej** [comment]
@vit9696, Framework HII compatibility issue with IFRExtractor-RS had been resolved. It's up to you now to archive this repo or continue to support it.

**Comment by NikolajSchlej** [comment]
@Falcosc, v1.4.0 of IFRExtractor-RS provides a verbose mode (```ifrextractor /path/to/file.bin verbose```) that outputs both offsets and raw opcode bytes (useful for crating patches).
Please check it out and see if UEFI-Editor project can use it.

**Comment by NikolajSchlej** [comment]
Talked to @vit9696 via IM, closing this as completed, and archiving the repo.
